/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.tablahash;

import javax.swing.JOptionPane;

/**
 *
 * @author luis2
 */
public class JFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public JFrame() {
        initComponents();
        BlockInitial();
    }
boolean flag=true;
TablaHash tablaH;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Inserción = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Mostrar = new javax.swing.JButton();
        Asignacion = new javax.swing.JTextField();
        IDdd = new javax.swing.JTextField();
        Asignaciontxt = new javax.swing.JLabel();
        IDtxt = new javax.swing.JLabel();
        ListaMostrar = new java.awt.List();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Inserción.setText("Insertar");
        Inserción.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserciónActionPerformed(evt);
            }
        });

        Buscar.setText("Busqueda");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Mostrar.setText("Visualizar ");
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });

        IDtxt.setText("ID");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Año", "Genero", "Ambos" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Inserción)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Buscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Eliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Mostrar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Asignaciontxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(IDtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Asignacion)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(IDdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ListaMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inserción)
                    .addComponent(Buscar)
                    .addComponent(Eliminar)
                    .addComponent(Mostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Asignacion)
                    .addComponent(Asignaciontxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDdd)
                    .addComponent(IDtxt)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addComponent(ListaMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BlockInitial()
    {
        Buscar.setVisible(false);
        Eliminar.setVisible(false);
        Mostrar.setVisible(false);
        Asignaciontxt.setText("Ingresa Tamaño");
        IDdd.setVisible(false);
        IDtxt.setVisible(false);
        jComboBox2.setVisible(false);
        Asignacion.setText("");
    }
    private void InserciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserciónActionPerformed
        // TODO add your handling code here:
        if(flag)
        {
             if(Asignacion.getText()!="")
            {
            tablaH = new TablaHash(Integer.parseInt(Asignacion.getText()));
            Asignaciontxt.setText("Nombre");
            Asignacion.setText("");
            RunButtons();
            flag=false;
            JOptionPane.showMessageDialog(this, "Porfavor llenar todos los campos de texto");
            }
            
        }
        else
        {
            if(Asignacion.getText()!="" && IDdd.getText()!="" && flag==false)
            {
            comparador(Asignacion.getText(),Integer.parseInt(IDdd.getText()));
            Asignacion.setText("");
            IDdd.setText("");
            JOptionPane.showMessageDialog(this, "Se ingresaron datos con exito");
            }
            Mostrar();
            
        }
    }//GEN-LAST:event_InserciónActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        ListaMostrar.clear();
        int buscado = Integer.parseInt(IDdd.getText());
                        for (int i = 0; i < tablaH.getMaximo(); i++) {
                            if(tablaH.tabla[i].libre==false)
                            {
                                for (int j = 0; j < tablaH.tabla[i].valores.size(); j++) {
                                    if(buscado==tablaH.tabla[i].valores.get(j).getID()){
                                    ListaMostrar.add("ID: "+tablaH.tabla[i].valores.get(j).getID().toString());
                                    ListaMostrar.add("Nombre: "+tablaH.tabla[i].valores.get(j).getNombre());
                                    ListaMostrar.add("Genero: "+tablaH.tabla[i].valores.get(j).getGenero());
                                    ListaMostrar.add("Año: "+tablaH.tabla[i].valores.get(j).getAnio());
                                }
                                }
                            }
                        }
                        if(ListaMostrar.getItemCount()==0){
                            ListaMostrar.add("No se encontro la pelicula");
                        }
                        
    }//GEN-LAST:event_BuscarActionPerformed
private void Mostrar()
{
    ListaMostrar.clear();
        int a=1;
                        for (int i = 0; i < tablaH.getMaximo(); i++) {
                            if(tablaH.tabla[i].libre==false)
                            {
                                ListaMostrar.add("#"+(a++)+"");  
                                for (int j = 0; j < tablaH.tabla[i].valores.size(); j++) {
                                    ListaMostrar.add("ID: "+tablaH.tabla[i].valores.get(j).getID().toString());
                                    ListaMostrar.add("Nombre: "+tablaH.tabla[i].valores.get(j).getNombre());
                                    ListaMostrar.add("Genero: "+tablaH.tabla[i].valores.get(j).getGenero());
                                    ListaMostrar.add("Año: "+tablaH.tabla[i].valores.get(j).getAnio());
                                }
                               // System.out.println("");
                            }
                            else{
                              //  System.out.println("0");
                            }
                        }
}
    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
        // TODO add your handling code here:
        ListaMostrar.clear();
        int a=1;
                        for (int i = 0; i < tablaH.getMaximo(); i++) {
                            if(tablaH.tabla[i].libre==false)
                            {
                                ListaMostrar.add("#"+(a++)+"");  
                                for (int j = 0; j < tablaH.tabla[i].valores.size(); j++) {
                                    ListaMostrar.add("ID: "+tablaH.tabla[i].valores.get(j).getID().toString());
                                    ListaMostrar.add("Nombre: "+tablaH.tabla[i].valores.get(j).getNombre());
                                    ListaMostrar.add("Genero: "+tablaH.tabla[i].valores.get(j).getGenero());
                                    ListaMostrar.add("Año: "+tablaH.tabla[i].valores.get(j).getAnio());
                                }
                               // System.out.println("");
                            }
                            else{
                              if(ListaMostrar.getItemCount()==0){
                            ListaMostrar.add("Aun no se ha agregado nada al inventario");
                        }
                            }
                        }
    }//GEN-LAST:event_MostrarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        int eliminar=Integer.parseInt(IDdd.getText());
        tablaH.eliminar(tablaH.HashPorID(eliminar),eliminar);
        Asignacion.setText("");
            IDdd.setText("");
    }//GEN-LAST:event_EliminarActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }
private void comparador(String Nombre, int ID)
{
    if("Ninguno"==jComboBox2.getSelectedItem().toString())
    {
        tablaH.insertar(Nombre,ID,"","");
    }
    if("Año"==jComboBox2.getSelectedItem().toString())
    {
        String anio = JOptionPane.showInputDialog("Escriba Año", "");
        tablaH.insertar(Nombre,ID,anio,"");
    }
    if("Genero"==jComboBox2.getSelectedItem().toString())
    {
        String gen = JOptionPane.showInputDialog("Escriba Genero", "");
        tablaH.insertar(Nombre,ID,"",gen);
    }
    if("Ambos"==jComboBox2.getSelectedItem().toString())
    {
        String anio = JOptionPane.showInputDialog("Escriba Año", "");
        String gen = JOptionPane.showInputDialog("Escriba Genero", "");
        tablaH.insertar(Nombre,ID,anio,gen);
    }

}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Asignacion;
    private javax.swing.JLabel Asignaciontxt;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField IDdd;
    private javax.swing.JLabel IDtxt;
    private javax.swing.JButton Inserción;
    private java.awt.List ListaMostrar;
    private javax.swing.JButton Mostrar;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void RunButtons() {
        Buscar.setVisible(true);
        Eliminar.setVisible(true);
        Mostrar.setVisible(true);
        IDdd.setVisible(true);
        IDtxt.setVisible(true);
        jComboBox2.setVisible(true);
    }
}
